server:
  port: 58000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.0.21:58761/eureka

spring:
  application:
    name: omok-gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://OMOK-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - Method=GET
        - id: project-service
          uri: lb://OMOK-PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
          filters:
#            - AddRequestHeader=project-request, project-request-header
#            - AddResponseHeader=project-response, project-response-header
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

token:
  secret: iW50hkbOkPd92kEi4Z+hdBtNlGoaUwI0Aa9UY+Fb5jZyQK7Sm1dbEIaRauzhHyu6NVOT6bUZwXk3tOhiBuggnA==
