server:
  port: 58000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:58761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:

        # 회원 서비스
        - id: user-service
          uri: lb://OMOK-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # 로그인용 권한
        - id: user-service
          uri: lb://OMOK-USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # 프로젝트 서비스
        - id: project-service
          uri: lb://OMOK-PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
          filters:
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}

        # 프로젝트 팀 서비스
        - id: projectmember-service
          uri: lb://OMOK-PROJECTMEMBER-SERVICE
          predicates:
            - Path=/projectmember-service/**
          filters:
            - RewritePath=/projectmember-service/(?<segment>.*), /$\{segment}

token:
  secret:
